id: PA33AEE39
initial_creation_type: input
source_metadata:
  title: Yeshe Tsogyal Series
  language: pt
  description: 'Texts related to Yeshe Tsogyal (ye shes mtsho rgyal), the consort
    of Guru Padmasambhava:'
  volume:
    f88f0db4bfb741949f389e96496bcf18:
      title: A Prayer to Khandro Yeshé Tsogyal
      parent: Prayers
    564fe162b589490ab28e0e9d8413f1f0:
      title: A Prayer to Lady Yeshe Tsogyal, the Mother
      parent: Prayers
    7f698bb2ce5349929c8f4b237bbaa651:
      title: A Prayer to Yumka Tsogyal
      parent: Prayers
    bcdd19e21c074213802a5390a3a5015f:
      title: Prayer to Yeshe Tsogyal
      parent: Prayers
    c0b4b4eff64549f0b904305820e70aa7:
      title: 'The Tambura’s Yearning Song of Devotion: A Prayer Summarizing Khandro
        Yeshe Tsogyal’s Life and Liberation'
      parent: Prayers
    6138d577b0f444a3b7aef209bd974b86:
      title: Yeshe Tsogyal's Prayer
      parent: Prayers
    afbbd56f034c4a58a6f8fa38f465c181:
      title: 'The Concentrated Essence: A Sādhana of Yeshe Tsogyal'
      parent: Sādhanas
created_at: '2022-03-01T02:03:05.121131'
last_modified_at: '2022-03-01T02:03:05.121134'
